import { and, gte, lte, eq, sql, type SQL } from 'drizzle-orm';
import type { SubmissionFilter } from '@proofdesk/shared';
import { submissions } from '../db/schema.js';

// ---------------------------------------------------------------------------
// buildWhere (implementation plan §6/§7). THE single function that translates a
// filter object into SQL. Both GET /api/submissions (listing) and
// POST /api/submissions/bulk-status (bulk mutation) use it, so the count the
// reviewer sees and the rows a bulk action touches can never disagree — they
// are generated by the same code, not two implementations that could drift.
// ---------------------------------------------------------------------------

// Boolean-mode operators (+ - < > ( ) ~ * " @) in raw user input can throw a
// syntax error instead of being treated as text. Strip them, then wrap each
// remaining token as +token* (require all terms, allow prefix matches) so a
// partial word like "grea" still finds "great".
const BOOLEAN_MODE_OPERATORS = /[+\-<>()~"@*]/g;

export function toBooleanQuery(q: string): string {
  return q
    .replace(BOOLEAN_MODE_OPERATORS, ' ')
    .split(/\s+/)
    .filter(Boolean)
    .map((token) => `+${token}*`)
    .join(' ');
}

export function buildWhere(filter: SubmissionFilter): SQL | undefined {
  const conds: SQL[] = [];

  if (filter.status) conds.push(eq(submissions.status, filter.status));
  if (filter.type) conds.push(eq(submissions.type, filter.type));
  if (filter.ratingMin !== undefined) conds.push(gte(submissions.rating, filter.ratingMin));
  if (filter.ratingMax !== undefined) conds.push(lte(submissions.rating, filter.ratingMax));
  if (filter.dateFrom) {
    const from = new Date(`${filter.dateFrom}T00:00:00.000`);
    if (!Number.isNaN(from.getTime())) conds.push(gte(submissions.submittedAt, from));
  }
  if (filter.dateTo) {
    // Inclusive end-of-day so a date range of X..Y includes everything on Y.
    const to = new Date(`${filter.dateTo}T23:59:59.999`);
    if (!Number.isNaN(to.getTime())) conds.push(lte(submissions.submittedAt, to));
  }
  if (filter.q) {
    const against = toBooleanQuery(filter.q);
    if (against) {
      // Column list must exactly match the FULLTEXT index definition.
      conds.push(
        sql`MATCH(${submissions.name}, ${submissions.company}, ${submissions.testimonialText}, ${submissions.email})
            AGAINST (${against} IN BOOLEAN MODE)`,
      );
    }
  }

  return conds.length ? and(...conds) : undefined;
}
